// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Service-storage
Service storage brands and cosmetics.


    Schemes:
      http
    Host: localhost
    BasePath: /api/storage
    Version: 0.0.1

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
