version: '3.7'

services:

  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    ports:
      - ${PG_PORT:-5432}:5432
    environment:
      POSTGRES_USER: "postgresql"
      POSTGRES_DB: "postgresql"
      POSTGRES_PASSWORD: postgresql

  redis:
    container_name: redis
    restart: always
    image: redis:5.0
    command:
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASS:-""}'
    ports:
      - "6379:6379"

#  storage:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      image: storage
#      container_name: storage
#      restart: always
#      entrypoint: /storage
#      volumes:
#        - ./upload:/upload
#      command:
#        - "--db.host=postgresql"
#        - "--sessionStore.host=redis"
#      ports:
#        - "8080:8080"
