// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BrandCreateHandlerFunc turns a function with the right signature into a brand create handler
type BrandCreateHandlerFunc func(BrandCreateParams, *string) BrandCreateResponder

// Handle executing the request and returning a response
func (fn BrandCreateHandlerFunc) Handle(params BrandCreateParams, principal *string) BrandCreateResponder {
	return fn(params, principal)
}

// BrandCreateHandler interface for that can handle valid brand create params
type BrandCreateHandler interface {
	Handle(BrandCreateParams, *string) BrandCreateResponder
}

// NewBrandCreate creates a new http.Handler for the brand create operation
func NewBrandCreate(ctx *middleware.Context, handler BrandCreateHandler) *BrandCreate {
	return &BrandCreate{Context: ctx, Handler: handler}
}

/*BrandCreate swagger:route POST /brand brandCreate

Create new brand

*/
type BrandCreate struct {
	Context *middleware.Context
	Handler BrandCreateHandler
}

func (o *BrandCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBrandCreateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *string
	if uprinc != nil {
		principal = uprinc.(*string) // this is really a string, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
