// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"

	models "storage/internal/api/models"
)

// ProductCreateOKCode is the HTTP code returned for type ProductCreateOK
const ProductCreateOKCode int = 200

/*ProductCreateOK The server successfully processed the request.

swagger:response productCreateOK
*/
type ProductCreateOK struct {

	/*
	  In: Body
	*/
	Payload *models.Success `json:"body,omitempty"`
}

// NewProductCreateOK creates ProductCreateOK with default headers values
func NewProductCreateOK() *ProductCreateOK {

	return &ProductCreateOK{}
}

// WithPayload adds the payload to the product create o k response
func (o *ProductCreateOK) WithPayload(payload *models.Success) *ProductCreateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the product create o k response
func (o *ProductCreateOK) SetPayload(payload *models.Success) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProductCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ProductCreateOK) ProductCreateResponder() {}

/*ProductCreateDefault Generic error response.

swagger:response productCreateDefault
*/
type ProductCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProductCreateDefault creates ProductCreateDefault with default headers values
func NewProductCreateDefault(code int) *ProductCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &ProductCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the product create default response
func (o *ProductCreateDefault) WithStatusCode(code int) *ProductCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the product create default response
func (o *ProductCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the product create default response
func (o *ProductCreateDefault) WithPayload(payload *models.Error) *ProductCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the product create default response
func (o *ProductCreateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProductCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ProductCreateDefault) ProductCreateResponder() {}

type ProductCreateNotImplementedResponder struct {
	middleware.Responder
}

func (*ProductCreateNotImplementedResponder) ProductCreateResponder() {}

func ProductCreateNotImplemented() ProductCreateResponder {
	return &ProductCreateNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.ProductCreate has not yet been implemented",
		),
	}
}

type ProductCreateResponder interface {
	middleware.Responder
	ProductCreateResponder()
}
