// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"

	models "storage/internal/api/models"
)

// ProductDeleteOKCode is the HTTP code returned for type ProductDeleteOK
const ProductDeleteOKCode int = 200

/*ProductDeleteOK The server successfully processed the request and is not returning any content.

swagger:response productDeleteOK
*/
type ProductDeleteOK struct {
}

// NewProductDeleteOK creates ProductDeleteOK with default headers values
func NewProductDeleteOK() *ProductDeleteOK {

	return &ProductDeleteOK{}
}

// WriteResponse to the client
func (o *ProductDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

func (o *ProductDeleteOK) ProductDeleteResponder() {}

/*ProductDeleteDefault Generic error response.

swagger:response productDeleteDefault
*/
type ProductDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProductDeleteDefault creates ProductDeleteDefault with default headers values
func NewProductDeleteDefault(code int) *ProductDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &ProductDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the product delete default response
func (o *ProductDeleteDefault) WithStatusCode(code int) *ProductDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the product delete default response
func (o *ProductDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the product delete default response
func (o *ProductDeleteDefault) WithPayload(payload *models.Error) *ProductDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the product delete default response
func (o *ProductDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProductDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ProductDeleteDefault) ProductDeleteResponder() {}

type ProductDeleteNotImplementedResponder struct {
	middleware.Responder
}

func (*ProductDeleteNotImplementedResponder) ProductDeleteResponder() {}

func ProductDeleteNotImplemented() ProductDeleteResponder {
	return &ProductDeleteNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.ProductDelete has not yet been implemented",
		),
	}
}

type ProductDeleteResponder interface {
	middleware.Responder
	ProductDeleteResponder()
}
