// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ProductDELETEHandlerFunc turns a function with the right signature into a product d e l e t e handler
type ProductDELETEHandlerFunc func(ProductDELETEParams, *int) ProductDELETEResponder

// Handle executing the request and returning a response
func (fn ProductDELETEHandlerFunc) Handle(params ProductDELETEParams, principal *int) ProductDELETEResponder {
	return fn(params, principal)
}

// ProductDELETEHandler interface for that can handle valid product d e l e t e params
type ProductDELETEHandler interface {
	Handle(ProductDELETEParams, *int) ProductDELETEResponder
}

// NewProductDELETE creates a new http.Handler for the product d e l e t e operation
func NewProductDELETE(ctx *middleware.Context, handler ProductDELETEHandler) *ProductDELETE {
	return &ProductDELETE{Context: ctx, Handler: handler}
}

/*ProductDELETE swagger:route DELETE /product productDELETE

Delete product

*/
type ProductDELETE struct {
	Context *middleware.Context
	Handler ProductDELETEHandler
}

func (o *ProductDELETE) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewProductDELETEParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *int
	if uprinc != nil {
		principal = uprinc.(*int) // this is really a int, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
