// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ProductPOSTHandlerFunc turns a function with the right signature into a product p o s t handler
type ProductPOSTHandlerFunc func(ProductPOSTParams, *int) ProductPOSTResponder

// Handle executing the request and returning a response
func (fn ProductPOSTHandlerFunc) Handle(params ProductPOSTParams, principal *int) ProductPOSTResponder {
	return fn(params, principal)
}

// ProductPOSTHandler interface for that can handle valid product p o s t params
type ProductPOSTHandler interface {
	Handle(ProductPOSTParams, *int) ProductPOSTResponder
}

// NewProductPOST creates a new http.Handler for the product p o s t operation
func NewProductPOST(ctx *middleware.Context, handler ProductPOSTHandler) *ProductPOST {
	return &ProductPOST{Context: ctx, Handler: handler}
}

/*ProductPOST swagger:route POST /product productPOST

Create new product

*/
type ProductPOST struct {
	Context *middleware.Context
	Handler ProductPOSTHandler
}

func (o *ProductPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewProductPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *int
	if uprinc != nil {
		principal = uprinc.(*int) // this is really a int, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
