// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"io"
	"net/http"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"

	"search/internal/api/restapi/operations"
)

func BuildAPI(
	swaggerSpec *loads.Document,
	ServeError func(http.ResponseWriter, *http.Request, error),
	Logger func(string, ...interface{}),

	JSONConsumer func(r io.Reader, target interface{}) error,

	JSONProducer func(w io.Writer, data interface{}) error,

	BrandList func(params operations.BrandListParams) operations.BrandListResponder,
	ListProduct func(params operations.ListProductParams) operations.ListProductResponder,
	Product func(params operations.ProductParams) operations.ProductResponder,

	ServerShutdown func(),

) *operations.ServiceSearchAPI {
	api := operations.NewServiceSearchAPI(swaggerSpec)

	if ServeError != nil {
		api.ServeError = errors.ServeError
	}

	if Logger != nil {
		api.Logger = Logger
	}

	if JSONConsumer != nil {
		api.JSONConsumer = runtime.ConsumerFunc(JSONConsumer)
	}

	if JSONProducer != nil {
		api.JSONProducer = runtime.ProducerFunc(JSONProducer)
	}

	if BrandList != nil {
		api.BrandListHandler = operations.BrandListHandlerFunc(BrandList)
	}

	if ListProduct != nil {
		api.ListProductHandler = operations.ListProductHandlerFunc(ListProduct)
	}

	if Product != nil {
		api.ProductHandler = operations.ProductHandlerFunc(Product)
	}

	if ServerShutdown != nil {
		api.ServerShutdown = ServerShutdown
	}

	return api
}
