// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Service-search
Service search and information.


    Schemes:
      http
    Host: localhost
    BasePath: /api/search
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
