// Code generated by protoc-gen-go. DO NOT EDIT.
// source: susi_storage.proto

package channels

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Since struct {
	UNIX                 int64    `protobuf:"varint,1,opt,name=UNIX,proto3" json:"UNIX,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Since) Reset()         { *m = Since{} }
func (m *Since) String() string { return proto.CompactTextString(m) }
func (*Since) ProtoMessage()    {}
func (*Since) Descriptor() ([]byte, []int) {
	return fileDescriptor_36093c7a34f43a64, []int{0}
}

func (m *Since) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Since.Unmarshal(m, b)
}
func (m *Since) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Since.Marshal(b, m, deterministic)
}
func (m *Since) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Since.Merge(m, src)
}
func (m *Since) XXX_Size() int {
	return xxx_messageInfo_Since.Size(m)
}
func (m *Since) XXX_DiscardUnknown() {
	xxx_messageInfo_Since.DiscardUnknown(m)
}

var xxx_messageInfo_Since proto.InternalMessageInfo

func (m *Since) GetUNIX() int64 {
	if m != nil {
		return m.UNIX
	}
	return 0
}

type ProductEvent struct {
	// Types that are valid to be assigned to Event:
	//	*ProductEvent_Set
	//	*ProductEvent_Del
	Event                isProductEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProductEvent) Reset()         { *m = ProductEvent{} }
func (m *ProductEvent) String() string { return proto.CompactTextString(m) }
func (*ProductEvent) ProtoMessage()    {}
func (*ProductEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_36093c7a34f43a64, []int{1}
}

func (m *ProductEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductEvent.Unmarshal(m, b)
}
func (m *ProductEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductEvent.Marshal(b, m, deterministic)
}
func (m *ProductEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductEvent.Merge(m, src)
}
func (m *ProductEvent) XXX_Size() int {
	return xxx_messageInfo_ProductEvent.Size(m)
}
func (m *ProductEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ProductEvent proto.InternalMessageInfo

type isProductEvent_Event interface {
	isProductEvent_Event()
}

type ProductEvent_Set struct {
	Set *SetProduct `protobuf:"bytes,1,opt,name=set,proto3,oneof"`
}

type ProductEvent_Del struct {
	Del *DelProduct `protobuf:"bytes,2,opt,name=del,proto3,oneof"`
}

func (*ProductEvent_Set) isProductEvent_Event() {}

func (*ProductEvent_Del) isProductEvent_Event() {}

func (m *ProductEvent) GetEvent() isProductEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ProductEvent) GetSet() *SetProduct {
	if x, ok := m.GetEvent().(*ProductEvent_Set); ok {
		return x.Set
	}
	return nil
}

func (m *ProductEvent) GetDel() *DelProduct {
	if x, ok := m.GetEvent().(*ProductEvent_Del); ok {
		return x.Del
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProductEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProductEvent_Set)(nil),
		(*ProductEvent_Del)(nil),
	}
}

type SetProduct struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Apply                string   `protobuf:"bytes,5,opt,name=apply,proto3" json:"apply,omitempty"`
	Price                int32    `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Avatar               string   `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProduct) Reset()         { *m = SetProduct{} }
func (m *SetProduct) String() string { return proto.CompactTextString(m) }
func (*SetProduct) ProtoMessage()    {}
func (*SetProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_36093c7a34f43a64, []int{2}
}

func (m *SetProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProduct.Unmarshal(m, b)
}
func (m *SetProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProduct.Marshal(b, m, deterministic)
}
func (m *SetProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProduct.Merge(m, src)
}
func (m *SetProduct) XXX_Size() int {
	return xxx_messageInfo_SetProduct.Size(m)
}
func (m *SetProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProduct.DiscardUnknown(m)
}

var xxx_messageInfo_SetProduct proto.InternalMessageInfo

func (m *SetProduct) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SetProduct) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *SetProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetProduct) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SetProduct) GetApply() string {
	if m != nil {
		return m.Apply
	}
	return ""
}

func (m *SetProduct) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SetProduct) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type DelProduct struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelProduct) Reset()         { *m = DelProduct{} }
func (m *DelProduct) String() string { return proto.CompactTextString(m) }
func (*DelProduct) ProtoMessage()    {}
func (*DelProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_36093c7a34f43a64, []int{3}
}

func (m *DelProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelProduct.Unmarshal(m, b)
}
func (m *DelProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelProduct.Marshal(b, m, deterministic)
}
func (m *DelProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelProduct.Merge(m, src)
}
func (m *DelProduct) XXX_Size() int {
	return xxx_messageInfo_DelProduct.Size(m)
}
func (m *DelProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_DelProduct.DiscardUnknown(m)
}

var xxx_messageInfo_DelProduct proto.InternalMessageInfo

func (m *DelProduct) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Brands struct {
	Brands               []*Brand `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Brands) Reset()         { *m = Brands{} }
func (m *Brands) String() string { return proto.CompactTextString(m) }
func (*Brands) ProtoMessage()    {}
func (*Brands) Descriptor() ([]byte, []int) {
	return fileDescriptor_36093c7a34f43a64, []int{4}
}

func (m *Brands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brands.Unmarshal(m, b)
}
func (m *Brands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brands.Marshal(b, m, deterministic)
}
func (m *Brands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brands.Merge(m, src)
}
func (m *Brands) XXX_Size() int {
	return xxx_messageInfo_Brands.Size(m)
}
func (m *Brands) XXX_DiscardUnknown() {
	xxx_messageInfo_Brands.DiscardUnknown(m)
}

var xxx_messageInfo_Brands proto.InternalMessageInfo

func (m *Brands) GetBrands() []*Brand {
	if m != nil {
		return m.Brands
	}
	return nil
}

type Brand struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Brand) Reset()         { *m = Brand{} }
func (m *Brand) String() string { return proto.CompactTextString(m) }
func (*Brand) ProtoMessage()    {}
func (*Brand) Descriptor() ([]byte, []int) {
	return fileDescriptor_36093c7a34f43a64, []int{5}
}

func (m *Brand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brand.Unmarshal(m, b)
}
func (m *Brand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brand.Marshal(b, m, deterministic)
}
func (m *Brand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brand.Merge(m, src)
}
func (m *Brand) XXX_Size() int {
	return xxx_messageInfo_Brand.Size(m)
}
func (m *Brand) XXX_DiscardUnknown() {
	xxx_messageInfo_Brand.DiscardUnknown(m)
}

var xxx_messageInfo_Brand proto.InternalMessageInfo

func (m *Brand) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Brand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Since)(nil), "channels.Since")
	proto.RegisterType((*ProductEvent)(nil), "channels.ProductEvent")
	proto.RegisterType((*SetProduct)(nil), "channels.SetProduct")
	proto.RegisterType((*DelProduct)(nil), "channels.DelProduct")
	proto.RegisterType((*Brands)(nil), "channels.Brands")
	proto.RegisterType((*Brand)(nil), "channels.Brand")
}

func init() { proto.RegisterFile("susi_storage.proto", fileDescriptor_36093c7a34f43a64) }

var fileDescriptor_36093c7a34f43a64 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x4b, 0xeb, 0x40,
	0x10, 0xc6, 0x5f, 0x92, 0x26, 0x7d, 0x9d, 0x3e, 0x9e, 0xb2, 0x94, 0xb2, 0xa8, 0x87, 0x92, 0x8b,
	0x05, 0x21, 0x68, 0x3d, 0x78, 0xaf, 0x4a, 0xf5, 0x22, 0x92, 0x22, 0x78, 0x93, 0x6d, 0x32, 0xb4,
	0x8b, 0x71, 0x13, 0x76, 0xb7, 0x05, 0xff, 0x27, 0xff, 0x48, 0xd9, 0x49, 0x4a, 0x42, 0x7b, 0xdb,
	0xf9, 0xf6, 0x97, 0x6f, 0xbe, 0xc9, 0x2c, 0x30, 0xb3, 0x35, 0xf2, 0xc3, 0xd8, 0x52, 0x8b, 0x35,
	0x26, 0x95, 0x2e, 0x6d, 0xc9, 0xfe, 0x66, 0x1b, 0xa1, 0x14, 0x16, 0x26, 0x3e, 0x87, 0x70, 0x29,
	0x55, 0x86, 0x8c, 0x41, 0xef, 0xed, 0xe5, 0xf9, 0x9d, 0x7b, 0x13, 0x6f, 0x1a, 0xa4, 0x74, 0x8e,
	0x3f, 0xe1, 0xdf, 0xab, 0x2e, 0xf3, 0x6d, 0x66, 0x1f, 0x77, 0xa8, 0x2c, 0x9b, 0x42, 0x60, 0xd0,
	0x12, 0x32, 0x9c, 0x8d, 0x92, 0xbd, 0x49, 0xb2, 0x44, 0xdb, 0x70, 0x4f, 0x7f, 0x52, 0x87, 0x38,
	0x32, 0xc7, 0x82, 0xfb, 0x87, 0xe4, 0x03, 0x16, 0x1d, 0x32, 0xc7, 0x62, 0xde, 0x87, 0x10, 0x9d,
	0x79, 0xfc, 0xe3, 0x01, 0xb4, 0x46, 0xec, 0x3f, 0xf8, 0x32, 0xa7, 0x56, 0x61, 0xea, 0xcb, 0x9c,
	0x8d, 0x20, 0x5c, 0x69, 0xa1, 0x72, 0xf2, 0x1c, 0xa4, 0x75, 0xe1, 0x52, 0x2b, 0xf1, 0x85, 0x3c,
	0x20, 0x91, 0xce, 0x6c, 0x02, 0xc3, 0x1c, 0x4d, 0xa6, 0x65, 0x65, 0x65, 0xa9, 0x78, 0x8f, 0xae,
	0xba, 0x92, 0xf3, 0x12, 0x55, 0x55, 0x7c, 0xf3, 0xb0, 0xf6, 0xa2, 0xc2, 0xa9, 0x95, 0x96, 0x19,
	0xf2, 0x88, 0x9a, 0xd6, 0x05, 0x1b, 0x43, 0x24, 0x76, 0xc2, 0x0a, 0xcd, 0xfb, 0x04, 0x37, 0x55,
	0x7c, 0x01, 0xd0, 0x0e, 0x73, 0x98, 0x36, 0xbe, 0x81, 0x68, 0xee, 0x02, 0x1a, 0x76, 0x09, 0x11,
	0x45, 0x35, 0xdc, 0x9b, 0x04, 0xd3, 0xe1, 0xec, 0xa4, 0xfd, 0x19, 0x44, 0xa4, 0xcd, 0x75, 0x7c,
	0x05, 0x21, 0x09, 0x47, 0x93, 0xef, 0x67, 0xf4, 0xdb, 0x19, 0x67, 0x1a, 0xfa, 0xcb, 0x7a, 0xa3,
	0xec, 0x0e, 0x60, 0x81, 0xf6, 0x7e, 0x23, 0xd4, 0x1a, 0x0d, 0xeb, 0xd8, 0xd3, 0x5e, 0xcf, 0xc6,
	0xad, 0xd0, 0xdd, 0xe5, 0xb5, 0xc7, 0x12, 0x18, 0x2c, 0xd0, 0x36, 0x31, 0x8f, 0xbe, 0x3b, 0x3d,
	0xc8, 0x69, 0x56, 0x11, 0xbd, 0x9d, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0xa6, 0xf0,
	0x03, 0x51, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	GetChanges(ctx context.Context, in *Since, opts ...grpc.CallOption) (Storage_GetChangesClient, error)
	GetBrands(ctx context.Context, in *Since, opts ...grpc.CallOption) (*Brands, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) GetChanges(ctx context.Context, in *Since, opts ...grpc.CallOption) (Storage_GetChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Storage_serviceDesc.Streams[0], "/channels.Storage/GetChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageGetChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_GetChangesClient interface {
	Recv() (*ProductEvent, error)
	grpc.ClientStream
}

type storageGetChangesClient struct {
	grpc.ClientStream
}

func (x *storageGetChangesClient) Recv() (*ProductEvent, error) {
	m := new(ProductEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) GetBrands(ctx context.Context, in *Since, opts ...grpc.CallOption) (*Brands, error) {
	out := new(Brands)
	err := c.cc.Invoke(ctx, "/channels.Storage/GetBrands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	GetChanges(*Since, Storage_GetChangesServer) error
	GetBrands(context.Context, *Since) (*Brands, error)
}

// UnimplementedStorageServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (*UnimplementedStorageServer) GetChanges(req *Since, srv Storage_GetChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetChanges not implemented")
}
func (*UnimplementedStorageServer) GetBrands(ctx context.Context, req *Since) (*Brands, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrands not implemented")
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_GetChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Since)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).GetChanges(m, &storageGetChangesServer{stream})
}

type Storage_GetChangesServer interface {
	Send(*ProductEvent) error
	grpc.ServerStream
}

type storageGetChangesServer struct {
	grpc.ServerStream
}

func (x *storageGetChangesServer) Send(m *ProductEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _Storage_GetBrands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Since)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetBrands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/channels.Storage/GetBrands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetBrands(ctx, req.(*Since))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "channels.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBrands",
			Handler:    _Storage_GetBrands_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetChanges",
			Handler:       _Storage_GetChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "susi_storage.proto",
}
