swagger: '2.0'

consumes:
  - application/json
produces:
  - application/json

info:
  version: 0.0.1
  title: Service-search
  description: Service search and information.

basePath: /api/search

schemes:
  - http

responses:
  ListBrand:
    description: Getting a list of brands.
    schema:
      type: array
      items:
        $ref: '#/definitions/Brand'

  ListProduct:
    description: Receive a list of products.
    schema:
      type: array
      items:
        $ref: '#/definitions/Product'

  OneProduct:
    description: Getting one product.
    schema:
      $ref: '#/definitions/Product'

  GenericError:
    description: Generic error response.
    schema:
      $ref: '#/definitions/Error'

paths:

  /brand:
    get:
      description: "Get list brand"
      operationId: brandList

      responses:
        '200':  {$ref: '#/responses/ListBrand'}
        default: {$ref: '#/responses/GenericError'}

  /product/{productID}:
    get:
      operationId: product
      parameters:
        - in: path
          name: productID
          description: Track ID.
          required: true
          type: integer
      responses:
        '200':  {$ref: '#/responses/OneProduct'}
        default: {$ref: '#/responses/GenericError'}

  /product:
    get:
      operationId: listProduct
      parameters:
        - name: query
          type: string
          in: query
        - name: brand
          type: integer
          in: query
        - name: limit
          type: integer
          in: query
          default: 25
        - name: offset
          type: integer
          in: query
          default: 0
      responses:
        '200':  {$ref: '#/responses/ListProduct'}
        default: {$ref: '#/responses/GenericError'}

definitions:

  Brand:
    type: object
    required:
      - id
      - name
    properties:
      id:
        $ref: '#/definitions/ID'
      name:
        type: string

  Product:
    type: object
    required:
      - id
      - name
      - description
      - apply
      - price
    properties:
      id:
        $ref: '#/definitions/ID'
      name:
        type: string
        minLength: 1
        maxLength: 100
      description:
        type: string
      apply:
        type: string
      price:
        type: integer
      url:
        type: string

  ID:
    type: integer
    description: Object ID.

  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        description: Either same as HTTP Status Code.
        type: integer
        format: int32
      message:
        type: string
