// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/ZergsLaw/korean/src/internal/api/models"
)

// BrandDELETEOKCode is the HTTP code returned for type BrandDELETEOK
const BrandDELETEOKCode int = 200

/*BrandDELETEOK The server successfully processed the request and is not returning any content.

swagger:response brandDELETEOK
*/
type BrandDELETEOK struct {
}

// NewBrandDELETEOK creates BrandDELETEOK with default headers values
func NewBrandDELETEOK() *BrandDELETEOK {

	return &BrandDELETEOK{}
}

// WriteResponse to the client
func (o *BrandDELETEOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

func (o *BrandDELETEOK) BrandDELETEResponder() {}

/*BrandDELETEDefault Generic error response.

swagger:response brandDELETEDefault
*/
type BrandDELETEDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBrandDELETEDefault creates BrandDELETEDefault with default headers values
func NewBrandDELETEDefault(code int) *BrandDELETEDefault {
	if code <= 0 {
		code = 500
	}

	return &BrandDELETEDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the brand d e l e t e default response
func (o *BrandDELETEDefault) WithStatusCode(code int) *BrandDELETEDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the brand d e l e t e default response
func (o *BrandDELETEDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the brand d e l e t e default response
func (o *BrandDELETEDefault) WithPayload(payload *models.Error) *BrandDELETEDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the brand d e l e t e default response
func (o *BrandDELETEDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BrandDELETEDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *BrandDELETEDefault) BrandDELETEResponder() {}

type BrandDELETENotImplementedResponder struct {
	middleware.Responder
}

func (*BrandDELETENotImplementedResponder) BrandDELETEResponder() {}

func BrandDELETENotImplemented() BrandDELETEResponder {
	return &BrandDELETENotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.BrandDELETE has not yet been implemented",
		),
	}
}

type BrandDELETEResponder interface {
	middleware.Responder
	BrandDELETEResponder()
}
