// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/ZergsLaw/korean/src/internal/api/models"
)

// ProductOKCode is the HTTP code returned for type ProductOK
const ProductOKCode int = 200

/*ProductOK Getting one product.

swagger:response productOK
*/
type ProductOK struct {

	/*
	  In: Body
	*/
	Payload *models.Product `json:"body,omitempty"`
}

// NewProductOK creates ProductOK with default headers values
func NewProductOK() *ProductOK {

	return &ProductOK{}
}

// WithPayload adds the payload to the product o k response
func (o *ProductOK) WithPayload(payload *models.Product) *ProductOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the product o k response
func (o *ProductOK) SetPayload(payload *models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProductOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ProductOK) ProductResponder() {}

/*ProductDefault Generic error response.

swagger:response productDefault
*/
type ProductDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProductDefault creates ProductDefault with default headers values
func NewProductDefault(code int) *ProductDefault {
	if code <= 0 {
		code = 500
	}

	return &ProductDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the product default response
func (o *ProductDefault) WithStatusCode(code int) *ProductDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the product default response
func (o *ProductDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the product default response
func (o *ProductDefault) WithPayload(payload *models.Error) *ProductDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the product default response
func (o *ProductDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProductDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ProductDefault) ProductResponder() {}

type ProductNotImplementedResponder struct {
	middleware.Responder
}

func (*ProductNotImplementedResponder) ProductResponder() {}

func ProductNotImplemented() ProductResponder {
	return &ProductNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.Product has not yet been implemented",
		),
	}
}

type ProductResponder interface {
	middleware.Responder
	ProductResponder()
}
