// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/ZergsLaw/korean/src/internal/api/models"
)

// ProductDELETEOKCode is the HTTP code returned for type ProductDELETEOK
const ProductDELETEOKCode int = 200

/*ProductDELETEOK The server successfully processed the request and is not returning any content.

swagger:response productDELETEOK
*/
type ProductDELETEOK struct {
}

// NewProductDELETEOK creates ProductDELETEOK with default headers values
func NewProductDELETEOK() *ProductDELETEOK {

	return &ProductDELETEOK{}
}

// WriteResponse to the client
func (o *ProductDELETEOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

func (o *ProductDELETEOK) ProductDELETEResponder() {}

/*ProductDELETEDefault Generic error response.

swagger:response productDELETEDefault
*/
type ProductDELETEDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProductDELETEDefault creates ProductDELETEDefault with default headers values
func NewProductDELETEDefault(code int) *ProductDELETEDefault {
	if code <= 0 {
		code = 500
	}

	return &ProductDELETEDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the product d e l e t e default response
func (o *ProductDELETEDefault) WithStatusCode(code int) *ProductDELETEDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the product d e l e t e default response
func (o *ProductDELETEDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the product d e l e t e default response
func (o *ProductDELETEDefault) WithPayload(payload *models.Error) *ProductDELETEDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the product d e l e t e default response
func (o *ProductDELETEDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProductDELETEDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ProductDELETEDefault) ProductDELETEResponder() {}

type ProductDELETENotImplementedResponder struct {
	middleware.Responder
}

func (*ProductDELETENotImplementedResponder) ProductDELETEResponder() {}

func ProductDELETENotImplemented() ProductDELETEResponder {
	return &ProductDELETENotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.ProductDELETE has not yet been implemented",
		),
	}
}

type ProductDELETEResponder interface {
	middleware.Responder
	ProductDELETEResponder()
}
