// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/ZergsLaw/korean/internal/api/models"
)

// BrandPOSTOKCode is the HTTP code returned for type BrandPOSTOK
const BrandPOSTOKCode int = 200

/*BrandPOSTOK Getting a list of brands.

swagger:response brandPOSTOK
*/
type BrandPOSTOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Brand `json:"body,omitempty"`
}

// NewBrandPOSTOK creates BrandPOSTOK with default headers values
func NewBrandPOSTOK() *BrandPOSTOK {

	return &BrandPOSTOK{}
}

// WithPayload adds the payload to the brand p o s t o k response
func (o *BrandPOSTOK) WithPayload(payload []*models.Brand) *BrandPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the brand p o s t o k response
func (o *BrandPOSTOK) SetPayload(payload []*models.Brand) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BrandPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Brand, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *BrandPOSTOK) BrandPOSTResponder() {}

/*BrandPOSTDefault Generic error response.

swagger:response brandPOSTDefault
*/
type BrandPOSTDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBrandPOSTDefault creates BrandPOSTDefault with default headers values
func NewBrandPOSTDefault(code int) *BrandPOSTDefault {
	if code <= 0 {
		code = 500
	}

	return &BrandPOSTDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the brand p o s t default response
func (o *BrandPOSTDefault) WithStatusCode(code int) *BrandPOSTDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the brand p o s t default response
func (o *BrandPOSTDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the brand p o s t default response
func (o *BrandPOSTDefault) WithPayload(payload *models.Error) *BrandPOSTDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the brand p o s t default response
func (o *BrandPOSTDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BrandPOSTDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *BrandPOSTDefault) BrandPOSTResponder() {}

type BrandPOSTNotImplementedResponder struct {
	middleware.Responder
}

func (*BrandPOSTNotImplementedResponder) BrandPOSTResponder() {}

func BrandPOSTNotImplemented() BrandPOSTResponder {
	return &BrandPOSTNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.BrandPOST has not yet been implemented",
		),
	}
}

type BrandPOSTResponder interface {
	middleware.Responder
	BrandPOSTResponder()
}
