// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UploadAvatarProductHandlerFunc turns a function with the right signature into a upload avatar product handler
type UploadAvatarProductHandlerFunc func(UploadAvatarProductParams, *int) UploadAvatarProductResponder

// Handle executing the request and returning a response
func (fn UploadAvatarProductHandlerFunc) Handle(params UploadAvatarProductParams, principal *int) UploadAvatarProductResponder {
	return fn(params, principal)
}

// UploadAvatarProductHandler interface for that can handle valid upload avatar product params
type UploadAvatarProductHandler interface {
	Handle(UploadAvatarProductParams, *int) UploadAvatarProductResponder
}

// NewUploadAvatarProduct creates a new http.Handler for the upload avatar product operation
func NewUploadAvatarProduct(ctx *middleware.Context, handler UploadAvatarProductHandler) *UploadAvatarProduct {
	return &UploadAvatarProduct{Context: ctx, Handler: handler}
}

/*UploadAvatarProduct swagger:route PUT /avatar/{productID} uploadAvatarProduct

UploadAvatarProduct upload avatar product API

*/
type UploadAvatarProduct struct {
	Context *middleware.Context
	Handler UploadAvatarProductHandler
}

func (o *UploadAvatarProduct) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUploadAvatarProductParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *int
	if uprinc != nil {
		principal = uprinc.(*int) // this is really a int, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
